Ajax event handler erring on page load
JQuery loading on defer caused the ajaxSuccess event handler to fail registering: 
ReferenceError: $ is not defined

Update to check for DOM completion similar to how jquery handles the .ready() function.